{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeOperators #-}


module AgdaSearch.Web.Settings(parseSettings, Settings(..)) where

import Env


data Settings = MkSettings
  { port :: Int
  , dbPath :: FilePath
  , agdaSources :: FilePath
  } deriving Show


parser :: Parser Error Settings
parser =
  MkSettings <$> var auto "PORT" (def 3000 <> helpDef show <> help "port to bind to")
             <*> var str "DB_PATH" (help "path to the sqlite database as generated by agda-search")
             <*> var str "AGDA_SOURCES" (help "path to agda sources used to generate links to")

parseSettings :: IO Settings
parseSettings = Env.parse (header "Agda search web") parser
