{-# LANGUAGE DataKinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}


module AgdaSearch.Web.Settings(parseSettings, Settings(..)) where

import Env


data Settings = MkSettings
  { port :: Int
  , dbPathStdLib :: FilePath
  , dbPath1lab   :: FilePath
  , agdaSources :: FilePath
  } deriving Show


parser :: Parser Error Settings
parser =
  MkSettings <$> var auto "PORT" (def 3000 <> helpDef show <> help "port to bind to")
             <*> var str "DB_PATH_STD_LIB" (help "path to the sqlite database as generated by agda-search for stdlib")
             <*> var str "DB_PATH_1LAB" (help "path to the sqlite database as generated by agda-search for 1lab")
             <*> var str "AGDA_SOURCES" (help "path to agda sources used to generate links to")

parseSettings :: IO Settings
parseSettings = Env.parse (header "Agda search web") parser
