name: "Nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Local cache
      uses: actions/cache@v2
      with:
        path: /nix/store
        key: "${{ runner.os }}-nix-cache"
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: nix-build nix/create-db.nix
    - run: nix-shell --run "echo OK"
